config/routes.rb
Rails.application.routes.draw do
  resources :sports
  devise_for :users
  get "home/index"
  root "home#index"

  authenticate :user do
    get "/play", to: "pages#play"
    get "/moments", to: "pages#moments"
    get "/profile", to: "users#profile"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sport.rb
class Sport < ApplicationRecord
    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    profile_path # Redirects to /play after login
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path # Redirects to home after logout
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def play
  end

  def moments
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: %i[ show edit update destroy ]

  # GET /sports or /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1 or /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports or /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: "Sport was successfully created." }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1 or /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: "Sport was successfully updated." }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1 or /sports/1.json
  def destroy
    @sport.destroy!

    respond_to do |format|
      format.html { redirect_to sports_path, status: :see_other, notice: "Sport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def sport_params
      params.fetch(:sport, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/header/_navbar.html.erb
<nav class="bg-gray-200">
    <div class="w-3/4 mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 items-center justify-between">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <!-- Mobile menu button-->
                <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:ring-2 focus:ring-white focus:outline-hidden focus:ring-inset" aria-controls="mobile-menu" aria-expanded="false">
                    <span class="absolute -inset-0.5"></span>
                    <span class="sr-only">Open main menu</span>
                    <!--Icon when menu is closed.Menu open: "hidden", Menu closed: "block"-->
                    <svg class="block size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                    <!-- Icon when menu is open. Menu open: "block", Menu closed: "hidden" -->
                    <svg class="hidden size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
            <div class="w-[100%] flex items-center justify-around lg:gap-[14rem] sm:items-stretch sm:justify-start">
                <%= link_to root_path, class: "flex shrink-0 items-center" do %>
                <img class="h-8 w-auto" src="<%= asset_path('Icon.png') %>" alt="Play Heroes">
                <p class="text-3xl font-semibold ml-1">PlayHeroes</p>
                <% end %>

                <div class="mt-8 sm:ml-6 sm:block">
                    <ul class="flex space-x-4">
                        <li><%= link_to "Play", play_path, class: "rounded-md px-3 py-2 text-lg font-semibold text-gray-800 hover:bg-gray-700 hover:text-white" %></li>
                        <li><%= link_to "Moments", moments_path, class: "rounded-md px-3 py-2 text-lg font-semibold text-gray-800 hover:bg-gray-700 hover:text-white" %></li>
                        <li><%= link_to "Profile", profile_path, class: "rounded-md px-3 py-2 text-lg font-semibold text-gray-800 hover:bg-gray-700 hover:text-white" %></li>
                    </ul>
                </div>
                </p>
                <div class="absolute inset-y-0 right-0 flex items-center mb-6 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                    <% if controller_name == "sessions" && action_name == "new" %>
                    <!-- If on login page, show Sign Up button -->
                    <%= link_to "Sign Up", new_user_registration_path, class: "mt-6 px-4 py-2 bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg cursor-pointer" %>

                    <% elsif (controller_name == "registrations" && action_name == "new") || controller_name == "home" %>
                    <!-- If on signup page, show Login button -->
                    <%= link_to "Login", new_user_session_path, class: "mt-6 px-4 py-2 bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg cursor-pointer" %>
                    <% end %>

                    <!-- Default (If user is on other pages, show Logout or Profile) -->
                    <% if user_signed_in? && controller_name != "home" %>
                    <%= link_to "Logout", destroy_user_session_path, data: {"turbo-method": :delete }, class: "mt-6 px-4 py-2 bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg cursor-pointer" %>
                    <% end %>
                </div>




                <%
=begin%>
                <div class="absolute  inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
                    <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 focus:outline-hidden">
                        <span class="absolute -inset-1.5"></span>
                        <span class="sr-only">View notifications</span>
                        <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
                        </svg>
                    </button>

                    <!-- Profile dropdown -->
                    <div class="relative ml-3">
                        <div>
                            <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 focus:outline-hidden" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                                <span class="absolute -inset-1.5"></span>
                                <span class="sr-only">Open user menu</span>
                                <img class="size-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                            </button>
                        </div>
                        <div class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 ring-1 shadow-lg ring-black/5 focus:outline-hidden" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                            <!-- Active: "bg-gray-100 outline-hidden", Not Active: "" -->
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
                        </div>
                    </div>
                </div>
                <%
=end%>
            </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden" id="mobile-menu">
            <div class="space-y-1 px-2 pt-2 pb-3">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <a href="#" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">Play</a>
                <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Moments</a>
                <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Profile</a>
            </div>
        </div>
</nav>

app/views/home/index.html.erb
<div class="relative h-screen w-screen bg-cover bg-center bg-no-repeat" style="background-image: url('<%= asset_url("PlayHeroesLandingPage.png") %>');">

    <!-- Content on Top -->
    <div class="relative z-10 flex flex-col items-center justify-center h-full text-white text-center px-6">
        <h1 class="text-6xl font-bold">Play. Connect. Track.</h1>
        <h2 class="text-4xl mt-2  font-bold">Elevate your game with PlayHeroes!</h2>
        <p class="text-lg mt-2  max-w-2xl font-semibold">
            Find players, join tournaments, share your moments and </br> track your fitness! - all in one place
        </p>
        <%= link_to "/users/sign_up", class:"mt-6 px-6 py-3 bg-green-500 hover:bg-green-600 text-white font-semibold rounded-lg cursor-pointer" do %>
        Get Started
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>PlayHeroes | Where Sports meets Community!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= favicon_link_tag 'favicon.ico', type: 'image/x-icon', rel: 'shortcut icon' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'header/navbar' %>
    <%= yield %>
</body>

</html>

app/views/pages/moments.html.erb
<div>
    <h1 class="font-bold text-4xl">Moments</h1>
</div>

app/views/pages/play.html.erb
<div>
    <h1 class="font-bold text-4xl">Play</h1>
</div>

app/views/sports/_form.html.erb
<%= form_with(model: sport, class: "contents") do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul class="list-disc ml-6">
        <% sport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sports/_sport.html.erb
<div id="<%= dom_id sport %>">
    <%= sport.name %>
</div>

app/views/sports/edit.html.erb
<% content_for :title, "Editing sport" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sport</h1>

  <%= render "form", sport: @sport %>

  <%= link_to "Show this sport", @sport, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to sports", sports_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/sports/index.html.erb
<h2>All Sports</h2>
<ul>
    <% @sports.each do |sport| %>
    <li><%= sport.name %></li>
    <% end %>
</ul>

app/views/sports/new.html.erb
<% content_for :title, "New sport" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sport</h1>

  <%= render "form", sport: @sport %>

  <%= link_to "Back to sports", sports_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/sports/show.html.erb
<% content_for :title, "Showing sport" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing sport</h1>

  <%= render @sport %>

  <%= link_to "Edit this sport", edit_sport_path(@sport), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to sports", sports_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this sport", @sport, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>

app/views/users/profile.html.erb
<div>
    <h1 class="font-bold text-4xl">Profile</h1>
</div>